export const ptBRLocalization = {
  // Common
  SIGN_IN: "Entrar",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_DESCRIPTION: "Digite seu e-mail abaixo para acessar sua conta",
  SIGN_UP: "Criar Conta",
  SIGN_UP_ACTION: "Criar uma conta",
  SIGN_UP_DESCRIPTION: "Insira suas informações para criar uma conta",
  EMAIL: "E-mail",
  EMAIL_PLACEHOLDER: "seu@email.com",
  EMAIL_REQUIRED: "O e-mail é obrigatório",
  PASSWORD: "Senha",
  PASSWORD_PLACEHOLDER: "Senha",
  PASSWORD_REQUIRED: "A senha é obrigatória",
  DONT_HAVE_AN_ACCOUNT: "Não tem uma conta?",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  SIGN_IN_WITH: "Entrar com",
  OR_CONTINUE_WITH: "Ou continue com",
  NAME: "Nome",
  NAME_PLACEHOLDER: "Seu Nome",
  NAME_DESCRIPTION: "Por favor, digite seu nome completo.",
  NAME_INSTRUCTIONS: "Utilize no máximo 32 caracteres.",
  FORGOT_PASSWORD_LINK: "Esqueceu sua senha?",
  REMEMBER_ME: "Lembrar-me",
  CONTINUE: "Continuar",
  CANCEL: "Cancelar",
  UPDATE: "Atualizar",
  DELETE: "Excluir",
  DONE: "Concluído",
  SAVE: "Salvar",

  // Password Reset / Forgot Password
  FORGOT_PASSWORD: "Recuperar Senha",
  FORGOT_PASSWORD_ACTION: "Enviar link de recuperação",
  FORGOT_PASSWORD_DESCRIPTION: "Digite seu e-mail para redefinir sua senha",
  FORGOT_PASSWORD_EMAIL: "Verifique seu e-mail para acessar o link de redefinição de senha.",
  RESET_PASSWORD: "Redefinir Senha",
  RESET_PASSWORD_ACTION: "Salvar nova senha",
  RESET_PASSWORD_DESCRIPTION: "Digite sua nova senha abaixo",
  RESET_PASSWORD_SUCCESS: "Senha redefinida com sucesso",
  NEW_PASSWORD: "Nova Senha",
  NEW_PASSWORD_PLACEHOLDER: "Nova Senha",
  NEW_PASSWORD_REQUIRED: "A nova senha é obrigatória",
  CONFIRM_PASSWORD: "Confirmar Senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar Senha",
  CONFIRM_PASSWORD_REQUIRED: "A confirmação da senha é obrigatória",
  PASSWORDS_DO_NOT_MATCH: "As senhas não coincidem",

  // Verification
  VERIFY_YOUR_EMAIL: "Verifique seu E-mail",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Por favor, verifique seu endereço de e-mail. Caso não tenha recebido, clique no botão abaixo para reenviar.",
  RESEND_VERIFICATION_EMAIL: "Reenviar e-mail de verificação",
  EMAIL_VERIFICATION_SUCCESS: "E-mail verificado com sucesso.",
  EMAIL_VERIFICATION: "Verificação de E-mail",
  EMAIL_VERIFICATION_DESCRIPTION: "Por favor, verifique o código enviado ao seu e-mail.",
  
  // Magic Link
  MAGIC_LINK: "Link Mágico",
  MAGIC_LINK_ACTION: "Enviar link mágico",
  MAGIC_LINK_DESCRIPTION: "Digite seu e-mail para receber um link mágico",
  MAGIC_LINK_EMAIL: "Verifique seu e-mail para acessar o link mágico",

  // OTP
  EMAIL_OTP: "Código de E-mail",
  EMAIL_OTP_SEND_ACTION: "Enviar código",
  EMAIL_OTP_VERIFY_ACTION: "Verificar código",
  EMAIL_OTP_DESCRIPTION: "Digite seu e-mail para receber um código",
  EMAIL_OTP_VERIFICATION_SENT: "Por favor, verifique seu e-mail para o código de verificação.",

  // Errors & Validations
  IS_INVALID: "é inválido",
  IS_REQUIRED: "é obrigatório",
  INVALID_EMAIL: "E-mail inválido",
  INVALID_PASSWORD: "Senha inválida",
  INVALID_EMAIL_OR_PASSWORD: "E-mail ou senha inválidos",
  USER_NOT_FOUND: "Usuário não encontrado",
  USER_ALREADY_EXISTS: "O usuário já existe",
  PASSWORD_TOO_SHORT: "A senha é muito curta",
  PASSWORD_TOO_LONG: "A senha é muito longa",
  UNEXPECTED_ERROR: "Ocorreu um erro inesperado",
  SERVICE_UNAVAILABLE: "Serviço indisponível",
  TOO_MANY_ATTEMPTS: "Muitas tentativas. Tente novamente mais tarde.",

  // Auth UI labels
  APP: "Aplicativo",
  ACCOUNT: "Conta",
  ACCOUNTS: "Contas",
  ADD_ACCOUNT: "Adicionar Conta",
  CURRENT_SESSION: "Sessão Atual",
  SIGN_OUT: "Sair",
  SETTINGS: "Configurações",
  SECURITY: "Segurança",
  PRIVACY_POLICY: "Política de Privacidade",
  TERMS_OF_SERVICE: "Termos de Serviço",
  PROTECTED_BY_RECAPTCHA: "Protegido por reCAPTCHA.",
  BY_CONTINUING_YOU_AGREE: "Ao continuar, você concorda com os",

  // Two Factor
  TWO_FACTOR: "Autenticação de Dois Fatores",
  TWO_FACTOR_ACTION: "Verificar código",
  TWO_FACTOR_DESCRIPTION: "Por favor, digite seu código de acesso para continuar",
  ENABLE_TWO_FACTOR: "Ativar Dois Fatores",
  DISABLE_TWO_FACTOR: "Desativar Dois Fatores",
  BACKUP_CODES: "Códigos de Recuperação",
  BACKUP_CODE: "Código de Recuperação",
  BACKUP_CODE_PLACEHOLDER: "Código de Recuperação",
  BACKUP_CODE_REQUIRED: "O código de recuperação é obrigatório",

  // Others
  UPLOAD_AVATAR: "Enviar Avatar",
  DELETE_AVATAR: "Excluir Avatar",
  AVATAR_DESCRIPTION: "Clique no avatar para enviar uma imagem personalizada.",
  AVATAR_INSTRUCTIONS: "O avatar é opcional, mas fortemente recomendado.",
  OPTIONAL_BRACKETS: "(Opcional)",
  GO_BACK: "Voltar",
};
